#version: '3.8'
#services:
#  mysql:
#    image: mysql:latest
#    environment:
#      - MYSQL_DATABASE=m_movies_copy
#      - MYSQL_ROOT_PASSWORD=Baopro2001@
#    expose:
#      - 3307
#  cmm_movies:
#    image: cmm_movies:latest
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql