export const PACK_LIST_REQUEST = "PACK_LIST_REQUEST";
export const PACK_LIST_SUCCESS = "PACK_LIST_SUCCESS";
export const PACK_LIST_FAIL = "PACK_LIST_FAIL";

export const PACK_UPDATE_REQUEST = "PACK_UPDATE_REQUEST";
export const PACK_UPDATE_SUCCESS = "PACK_UPDATE_SUCCESS";
export const PACK_UPDATE_FAIL = "PACK_UPDATE_FAIL";
export const PACK_UPDATE_RESET = "PACK_UPDATE_RESET";
