export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";
export const REVIEW_LIST_RESET = "REVIEW_LIST_RESET";

export const REVIEW_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const REVIEW_UPDATE_REQUEST = "REVIEW_UPDATE_REQUEST";
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_REQUEST";
export const REVIEW_UPDATE_FAIL = "REVIEW_UPDATE_REQUEST";
